apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0fe2352f6995360a3