apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense
spec:
# One POD can contain multiple containers
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
