kind: Pod
apiVersion: v1
metadata:
  name: multi-containers
#namespace: expense
spec:
# One POD can contain multiple containers
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]
    
