
kind: Pod
apiVersion: v1
metadata:
  name: multi-containers
  labels:
   project: expense
   component: backend
   environment: dev
#namespace: expense
spec:
# One POD can contain multiple containers
  containers:
  - name: nginx
    image: nginx
