kind: Pod
apiVersion: v1
metadata:
  name: env
spec:
# One POD can contain multiple containers
  containers:
  - name: nginx
    image: nginx
    env:
    - name: "course"
      value: "DevOps"
    - name: trainer
      value: "siva kumar"