kind: Pod
apiVersion: v1
metadata:
  name: pod-config
  namespace: expense
spec:
  containers:
  - name: nginx
    image: nginx
# attaching ConfigMap to pod
    envFrom:
    - configMapRef:
         name: myconfig