kind: Pod
apiVersion: v1
metadata:
  name: pod-secret 
  namespace: expense
spec:
  containers:
  - name: nginx
    image: nginx
# attaching ConfigMap to pod
    envFrom:
    - secretRef:
       name: dotfile-secret