kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:  
    project: expense
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetport: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    project: expense
    environment: dev
spec:
# One POD can contain multiple containers
  containers:
  - name: nginx
    image: nginx



  
