kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:  
    name: nginx
    project: expense

  ports:
  - protocol: TCP
    port: 80
    targetport: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  project: expense

spec:
# One POD can contain multiple containers
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80


  
