apiVersion: v1
kind: Service
metadata:
  name: nginx 
spec:
  selector:  # labels are used to selectors
    project: expense
  ports:
    - protocol: TCP
      port: 80 # service port
      targetport: 8080 #target container port
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: backend
#   labels:
#     project: expense
# spec:
#   containers:
#   - name: nginx
#     image: nginx



  
