apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  selector:  # labels are used to selectors
    demo: np
  ports:
    - protocol: TCP
      port: 80         # The port exposed by the Service
      targetPort: 80  #target container port
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-np
  labels:
    demo: np
spec:
  containers:
  - name: nginx
    image: nginx



  
